# Load necessary packages
library(readxl)    # for reading Excel files
library(dplyr)     # for data manipulation

library(readxl)
Flooddd <- read_excel("C:/Users/USER/OneDrive/Desktop/Flooddd.xlsx")
Flooddd
file_path <- Flooddd
file_path
# Create binary target variable
# Create binary target variable
# Summary statistics for all variables
summary(file_path)


library(ggplot2)

# histogram of MonsoonIntensity
ggplot(file_path, aes(x = MonsoonIntensity)) +
  geom_histogram(binwidth = 0.5, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Monsoon Intensity", x = "Monsoon Intensity", y = "Count")

# Correlation matrix
cor_matrix <- cor(file_path)
print(round(cor_matrix, 2))

# Optional: visualize correlation heatmap
library(corrplot)
corrplot(cor_matrix, method = "color", type = "upper", tl.cex = 0.7)

file_path <- file_path %>%
mutate(Flood = ifelse(MonsoonIntensity >= 6, 1, 0))
file_path
summary(file_path)
num_cols <- names(select(file_path, -Flood))
file_path <- file_path %>%
  mutate(across(all_of(num_cols), scale))

# View scaled data (optional)
file_path

############################################################################
# Build logistic regression model using all predictors
model <- glm(Flood ~ ., data = file_path, family = binomial)

# View model summary
summary(model)

# Optional: view coefficients
coef(model)

# Predict probabilities
file_path$Flood_Prob <- predict(model, type = "response")
file_path

# also you can view head part
head(file_path[, c("Flood", "Flood_Prob")])


###We used a logistic regression model to estimate the probability of 
#flooding based on 20 environmental and climatic factors.
#The model coefficients indicate the influence of each variable.
#Predictions generated by the model can support decision-makers in identifying areas at risk.

####################################################

#MODEL EVALUATION 
#We now assess how well the logistic regression model performs. 
#Since this is a classification problem (Flood = 0 or 1), we'll evaluate it using:

# If you haven’t already, install required packages
install.packages("pROC")
install.packages("caret")

# Load libraries
library(pROC)
library(caret)

# Choose threshold (e.g., 0.5)
file_path $PredictedClass <- ifelse(file_path$Flood_Prob >= 0.5, 1, 0)

# Confusion Matrix
conf_matrix <- confusionMatrix(
  factor(file_path$PredictedClass),
  factor(file_path$Flood)
)
print(conf_matrix)

# ROC Curve and AUC
roc_obj <- roc(file_path$Flood, file_path$Flood_Prob)
plot(roc_obj, col = "blue", main = "ROC Curve")
auc_value <- auc(roc_obj)
cat("AUC =", auc_value)

####################################
install.packages("future.apply")
install.packages("recipes")
install.packages("caret")












